### PR TITLE
[BREAKING!!!!!] Migrate from deprecated Plexus component annotations to JSR 330 and Eclipse Sisu component

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

This follows https://eclipse.dev/sisu/org.eclipse.sisu.plexus/conversion-to-jsr330.html as Plexus component is deprecated. Sadly, it only works with 3.9.6+, I think for the same reason as Quarkus parent project has 3.9.6 for the minimum version: https://github.com/quarkusio/quarkus/blob/7a6b0eea9b844576ccfeca163aeff00e3d15c4c5/independent-projects/parent/pom.xml#L77

That however means that if we want to release this, we would only need to use it in projects that use 3.9.6+, which is not viable considering that min. 3.8.6 Maven version is now supported and that is what QE TS and QE FW use.

We don't need to make any changes in this project for now, so I think it is better to merge this rather as one day, we need it anyway (we must drop plexus component).

But if we need to release before we move the minimum Maven version, we either need to do it in a separate branch or temporarily revert this. The CI runs about 30 seconds so it is not exactly an issue.

Please check the relevant options

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dependency update
- [x] Refactoring
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Example scenarios has been updated / added
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
I think the main motivation for Maven 3.9.6 is around being able to use Java 17 to build plugins. Before that there were some hacks to build quarkus maven plugin using Java 11 while the rest of Quarkus project was built using Java 17.

**Comment by michalvavrik** [comment]
> I think the main motivation for Maven 3.9.6 is around being able to use Java 17 to build plugins. Before that there were some hacks to build quarkus maven plugin using Java 11 while the rest of Quarkus project was built using Java 17.

Alright, in that case I don't know why this requires 3.9.6 because I'd have to inspect Maven core release notes and docs. It seems like the right direction to go as https://mvnrepository.com/artifact/org.codehaus.plexus/plexus-component-annotations wasn't released since 2023 and Quarkus doesn't use it either.

**Comment by rsvoboda** [comment]
Agree, we could look into making mvn 3.9.6 the default for our infra. Possibly also for Jenkins side, but we need to look into 3.8 stream if it can work with it. I recall issue related to Maven 3.9, but I think it was for 3.2 stream (which is inactive)

**Comment by rsvoboda** [comment]
Seem the issue was with old 2.13 in the end, so bumping internal infra to use 3.9.6+ shouldn't be a problem at all

**Comment by michalvavrik** [comment]
> Seem the issue was with old 2.13 in the end, so bumping internal infra to use 3.9.6+ shouldn't be a problem at all

I actually thought that reason why we keep 3.8.6 is that we need to test supported minimum Maven version. So I thought it didn't depend on us.

**Pull request merged**
